image: hosttoday/ht-docker-node:npmts

stages:
- test
- release
- page

testLTS:
  stage: test
  script:
    - npmci test lts
  tags:
    - docker
    - lossless
    
testSTABLE:
  stage: test
  script:
    - npmci test stable
  tags:
    - docker
    - lossless

testLEGACY:
  stage: test
  script:
    - npmci test 0
  allow_failure: true

release:
  stage: release
  script:
    - npmci publish
  only:
    - tags
  tags:
    - docker
    - lossless
    
pages:
  stage: page
  script:
  - mkdir public
  - npmci npmpage
  artifacts:
    paths:
    - public
  tags:
    - docker
    - lossless